language: go
go:
- 1.4.2
addons:
  postgresql: 9.3
env:
  matrix:
  - AWS_REGION=us-east-1
  global:
  - secure: bd3901lw7TdgBVugfDfDOWC6MHR7VvpdCyHmpER7s1F913fnwUbuVSg1PNKeps/IEUoV31zE5+Cakq0EPACsLInnlTRgCSha9z6eFmCL7q9O+d87dMXHH7nBHmqRzfWHyqGBusgZQCmDTfTRFrgAl9yp4RAL3Yr+tmGMzNHvRTotFkGsuRnDGxG2c0K8oNFDgq6wzpd2BjYsUf9RUoRHNJd1Gc4aEKxkvsTmcWhvj/cTpb0Il2+Z2hsZzGRQf/rZY7jjpa0WMtCY95HikgkkXb/uq0EfgOKewuUpyIAQahfkCooTtfYTcbjK+XGMJrmwBZhqAgGQGoV9khB50RoPVDi66ZuqpNb70jASOPNgsj3VwNIurqADUblj+ECYpgO1YHm+ndJsZABxXDMvOipidyplk4r106h3ZshCDlCTDcld0yrPVYTe1Bo8PvDRzjvC0vFbz1roN1mWzditq9Fr9olVjtozMG38WCw1shsEDvuCD+2eef1fhYihLz1BgW+MdJUilQJaae1hUEUtWYDur3Z1bMSlsLXbLGMB35UQAl1sR+LmyCAyx2PVDu+exrQp3Hvq0kw9SQsy3pyQ1PL/LX9GXThz7DpPKAjy0opdgxABUO0iewISy1q2alr88BwdnKYlwL86Qn2PCihBrpWf2C/MkQJG9v9GTaVV1w3uwXY=
  - secure: qY0GFdlR0F4aepA66n+8qAGsVYwAUP9iRLoAdrwZFVtHu+1VH3wvMtt6uw29pKxpMblQ3ipwKIMLwPisTXZo7RWrMBtpyEmomyiyyLhOhl2rSO2uWh0wgWcloWVMgF2iR8vVz+Y/9hBz1Lo1NTuoLPG2IQ3A+ojS4NaIIWQ1dYS/nWCrd7f4yDPgJX7mI73F+LjWCdeYeVi7vpFAy7/b6ZWCkJzy6FPZVA1yC3HKDF0aWaYRxrg5nhvgLXimOKq78wbXKCIqERNYrXcquwnTbf0PbuK4NvdwvGCs7HW6r1AsWbC1UOzSvmlaLjRlli82DCGt/jBpL2ibGtpsEZItULBqfEwG7lx9QUH2ZMc3vu/ysH/ofknDBJTLSKe0mS2Rw0DVgKOjBJ0QG8up+GyNVAuMz5ntzs64YElwms2G6SqQpy36DVbu0F8L48eVx0gsm6EMI/c2IKL42Giy5uLVLv4b6d1CPoIZpdNQeWiJP8BVITyKSyu+zSfnIdSYbWB7b0HBMwbQAdyoPe4sukzGedtkwxLPm5/bga+Khu6W8NcJrYF6ZqMiq1YoewSJbnQm6d/8zjRoYC/vWKzGkGm9Ar76qgQ+Ty+T6FqilJaw6pk1X8twIFcsKSloRR4y5B/4W8dNTR+amyMKiEpb0eLZuuUdNZrOtfa5C/rvFVWVGzo=
services:
- postgresql
- redis-server
install:
- go get -d ./...
- go get -u github.com/stretchr/testify/assert
before_script:
- scripts/ci
script: go test ./...
after_success:
- go build .
- mkdir $HOME/dist
- mv erraroo $HOME/dist/
- tar czfv $HOME/dist/migrations.tar.gz db/migrations/*
deploy:
  provider: s3
  access_key_id: AKIAJBP3D3DM4VFVUFZQ
  secret_access_key:
    secure: YDQISBHAkbPiTd3nUfA5X5AcPlwUg5h/pwyxxykGYM4VeUAWwBUzASzu09itnpOmlLMO0OH/tDqWfZFoocMIdUfZQLqiwZBeDp9XnFTO2J1wkIeeGSz0Lxja8KP3cFHgu1ZEdBT8Q2543trQtAMe94k0zmn8iwpNtkarkN4E7hUz8DGPXcaCoU+0DoY/hJxs9Y0in1PW+UMcHQfvPB30mWd22rcMrRgOO+sR6C8Vl/FGe4tlnCVzyJo0KBHFaqVPBvuK0KXbn6iNaVvwUE4NFNJzXKkyMkddtE7i0qT3tmVK6nJVrkVG8+qJVhpWraJRueQROFfKO66H/N7txR04CHkrCGO2c74DovqxxetUwnMvdzI6YVMPQSh1v8sHF6EaMX/W7ZDmJwEdesY/oDiX700wkIiZzN76YrCt5GeqbEtfZhLTX8mKlVX2TXxwTTaOGRg6UxtKmZ1gZdrlwhmk3KL6WRi2r2wrBDVnMm/1OXybhW9qBaCNd2MLHFdC5tpePIZ2uGVPj5RTzHorC8hakqs/save9mcYL3J7FyVt5TCDAdGpXv8iqLxMM7kHZL9YzLu9WYBIETiA8auXev7g8vffU+hLcsS9yh66CTSsZi+F3BF3hnDkWsEQAgP/vJ4CUr9k2uMdgwJUsbpUJMWofEI2A5huWC72KsEqdY9XUik=
  bucket: builds.erraroo.com
  local_dir: "$HOME/dist"
  upload-dir: "$TRAVIS_BRANCH"
  acl: private
  on:
    repo: erraroo/erraroo
