language: go
go:
- 1.4.2
addons:
  postgresql: 9.3
env:
  matrix:
  - AWS_REGION=us-east-1
  global:
  - secure: bd3901lw7TdgBVugfDfDOWC6MHR7VvpdCyHmpER7s1F913fnwUbuVSg1PNKeps/IEUoV31zE5+Cakq0EPACsLInnlTRgCSha9z6eFmCL7q9O+d87dMXHH7nBHmqRzfWHyqGBusgZQCmDTfTRFrgAl9yp4RAL3Yr+tmGMzNHvRTotFkGsuRnDGxG2c0K8oNFDgq6wzpd2BjYsUf9RUoRHNJd1Gc4aEKxkvsTmcWhvj/cTpb0Il2+Z2hsZzGRQf/rZY7jjpa0WMtCY95HikgkkXb/uq0EfgOKewuUpyIAQahfkCooTtfYTcbjK+XGMJrmwBZhqAgGQGoV9khB50RoPVDi66ZuqpNb70jASOPNgsj3VwNIurqADUblj+ECYpgO1YHm+ndJsZABxXDMvOipidyplk4r106h3ZshCDlCTDcld0yrPVYTe1Bo8PvDRzjvC0vFbz1roN1mWzditq9Fr9olVjtozMG38WCw1shsEDvuCD+2eef1fhYihLz1BgW+MdJUilQJaae1hUEUtWYDur3Z1bMSlsLXbLGMB35UQAl1sR+LmyCAyx2PVDu+exrQp3Hvq0kw9SQsy3pyQ1PL/LX9GXThz7DpPKAjy0opdgxABUO0iewISy1q2alr88BwdnKYlwL86Qn2PCihBrpWf2C/MkQJG9v9GTaVV1w3uwXY=
  - secure: qY0GFdlR0F4aepA66n+8qAGsVYwAUP9iRLoAdrwZFVtHu+1VH3wvMtt6uw29pKxpMblQ3ipwKIMLwPisTXZo7RWrMBtpyEmomyiyyLhOhl2rSO2uWh0wgWcloWVMgF2iR8vVz+Y/9hBz1Lo1NTuoLPG2IQ3A+ojS4NaIIWQ1dYS/nWCrd7f4yDPgJX7mI73F+LjWCdeYeVi7vpFAy7/b6ZWCkJzy6FPZVA1yC3HKDF0aWaYRxrg5nhvgLXimOKq78wbXKCIqERNYrXcquwnTbf0PbuK4NvdwvGCs7HW6r1AsWbC1UOzSvmlaLjRlli82DCGt/jBpL2ibGtpsEZItULBqfEwG7lx9QUH2ZMc3vu/ysH/ofknDBJTLSKe0mS2Rw0DVgKOjBJ0QG8up+GyNVAuMz5ntzs64YElwms2G6SqQpy36DVbu0F8L48eVx0gsm6EMI/c2IKL42Giy5uLVLv4b6d1CPoIZpdNQeWiJP8BVITyKSyu+zSfnIdSYbWB7b0HBMwbQAdyoPe4sukzGedtkwxLPm5/bga+Khu6W8NcJrYF6ZqMiq1YoewSJbnQm6d/8zjRoYC/vWKzGkGm9Ar76qgQ+Ty+T6FqilJaw6pk1X8twIFcsKSloRR4y5B/4W8dNTR+amyMKiEpb0eLZuuUdNZrOtfa5C/rvFVWVGzo=
services:
- postgresql
- redis-server
install:
- go get -d ./...
- go get -u github.com/stretchr/testify/assert
before_script:
- scripts/ci
script: go test ./...
after_success:
- go build .
- mkdir $HOME/dist
- mv erraroo $HOME/dist/
- tar czfv $HOME/dist/migrations.tar.gz db/migrations/*
deploy:
  provider: s3
  access_key_id: AKIAIKH3ZAUJTZTMLHXA
  secret_access_key:
    secure: IAn2FSX+MOJNt3gsl/QUNvPN1J5mrOQPrx130IWOMF43lpZBQOiR5RKemyHPFwMgxXubd+XT6ffyaejJLUMPdVvUV6GKQac9ESAY7BgUFdQiMkvc1+rQbKRyo6vvNteis9044emp8Zw9MIYVi/26oUPuEqxgNzCjMFtZzow4GupkmM7kGRjZsZDqvSFPWYDup630v/bomBzB48LD+bZmouDviVPLmvffu4KJ2/Sf5vOH2Y6jIelgtwKxuuHAEoVnw11Zoj5rALXVi3QB8w1wpJEA/0onBANumq4oYdrZw2sS07nGlXLoHvHOFloV2XW+WBKuphy+o8K+xWIa1Oeqi/jXVMjClDup4zAtiUTga9JlA71GjuM13YiVa+mdH8nhx81Rdrri0f4N/dDykvautOmq1chtywuXcNLJV6SCyFaa6K1b9/+v4SMRA11yDJU+YO8QI9YDEf1s7aBHl8DlNm8Oao3WeCcI03hqi/1T4sz2qwbM8jifUUnDqSE8MC+zXzO9T3NOiGv/Dgg0fjdvGFihqzV/1RuJMoz8h3fViRf+bhv2AF2uE/RARCsKIJn/b8PAyi38pdNCplDNWyznk/9dqrg7kD2E6ms1ERpE0bge6krtozW2D+dc4DNL9t9yVeJdYwld6So6ZefHU1UvdQSmOczU7OxUKDaHgCSSi/E=
  bucket: backend.erraroo.com
  acl: private
  on:
    repo: erraroo/erraroo
